### ISSUE TITLE
Can't open library

### ISSUE THREAD

**Issue by DewNohMad** [datteroandrea/banedroid#2]
Hi, I need some help installing and running the application. When I tried installing the app into a android emulator, I receive this error message "Cannot open a library at 'FileMapping(from=D:\projects\libs\BaneNotation.jar, to=C:\Users\User\.gradle\caches\transforms-2\files-2.1\a63df7edd41ede3462247d903db5191d\jetified-BaneNotation.jar)'"

It also prompted can't resolve symbol "bane", I'm assuming there is the missing file of "com.bane.model"

**Comment by datteroandrea** [comment]
I was not expeting someone to notice this project, this brings me a lot of happiness! Sorry it's my fault i implemented a library called BaneNotation but forgot to add it to the libs of the project and i left it with the path of my disk.

**Comment by DewNohMad** [comment]
Thanks that would be great. I happen to come across your project, which I think it would help greatly in a school project of mine.

**Comment by datteroandrea** [comment]
[BaneNotation.zip](https://github.com/datteroandrea/banedroid/files/5950903/BaneNotation.zip)

Unzip it and import it, this should work fine i guess contact me if something goes wrong!

**Comment by linghu258** [comment]
Do I remove the original BaneNotation.jar in the project dependencies ?

**Comment by linghu258** [comment]
I have import the jar file and rebuild the project, but the error message still appear.

"Cannot open a library at 'FileMapping(from=D:\projects\libs\BaneNotation.jar, to=C:\Users\User\.gradle\caches\transforms-2\files-2.1\a63df7edd41ede3462247d903db5191d\jetified-BaneNotation.jar)'".

**Comment by DewNohMad** [comment]
Hey, thanks I could build and run the app into my android emulator. 

So can i ask how does the backdoor works ? From what I read, it is a background service so I'm assuming there is no physcial app installed into the android emulator ? So how do I open up the bane terminal to retrieve and see those information (SMS, contact, etc..) ?

**Comment by datteroandrea** [comment]
Yeah i was working on a better way to do this then i got into uni and forgot about this project, in the future i will probably update bane/banedroid, at the moment you have to edit a file .xml (i dont remember which one i will tell you more later) write your ip address in it (banedroid uses the technique of reverse tcp which means that the "victim" connects to the hacker server (bane terminal)), then install the banedroid to the emulator and just open up the bane terminal, usually you would like to use the hide command which basically hides the icon of the banedroid app and it makes the app look like an Android System Service, once the app is installed it autoboots whenever the phone restarts (like a system service) everything is invisible to the eye especially if you use the hide command.

**Comment by DewNohMad** [comment]
sure. If there is any documentation or steps how I could go about running the bane terminal that connects with the banedroid app that would be great. Thanks

**Comment by datteroandrea** [comment]
Yes [here](https://github.com/datteroandrea/bane/blob/master/README.md) (it's not perfect i know haha but the project isn't finished yet this is all i made at the moment), basically you just start the bane terminal through java -jar and use shell command then use the command start <port> to start the bane server on the specidifed port (if you dont specify the port it uses the default port which should be 8080) wait 5 seconds and use the show command to show which devices connected then use the command select <name> to select the connected device and start doing stuff.

**Comment by linghu258** [comment]
Can I also ask what do you mean by using install.sh to add bane as the command in Linux system?

**Comment by DewNohMad** [comment]
In the Bane repository, do I need to compile the Bane file into jar before executing the bane.jar as you had wrote under the setup ?

**Comment by datteroandrea** [comment]
yes, you need to compile it
